# Settings
title: Zapier Platform UI Documentation
description: 'Zapier Platform UI'
url: '' # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
baseurl: ''
slack_invite_url: 'https://join.slack.com/t/zapier-platform/shared_invite/enQtNTg1MjM5NjMzNTI3LTUyYWJjM2E1NTQ3NjViMGY0MzQ1NWJiMDJmNjcyNTJjMWRlOTg4MTNjOWEwNDFlNGExODU5OTgzNWM3MzZlMjk'

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Sass Settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: docs

collections:
  quickstart:
    output: true
    permalink: /:collection/:name
  docs:
    output: true
    permalink: /:collection/:name
  news:
    output: true
    permalink: /:collection/:name
  cli_docs:
    output: true
    permalink: /:collection/:name
  cli_tutorials:
    output: true
    permalink: /:collection/:name
  legacy:
    output: true
    permalink: /:collection/:name
  partners:
    output: true
    permalink: /:collection/:name
  partner_success_stories:
    output: true
    permalink: /:collection/:name
  partner_api:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ''
      type: 'quickstart'
    values:
      layout: default
  - scope:
      path: ''
      type: 'docs'
    values:
      layout: default
  - scope:
      path: ''
      type: 'news'
    values:
      layout: default
  - scope:
      path: ''
      type: 'cli_docs'
    values:
      layout: default
  - scope:
      path: ''
      type: 'cli_tutorials'
    values:
      layout: default
  - scope:
      path: ''
      type: 'legacy'
    values:
      layout: default
  - scope:
      path: ''
      type: 'partners'
    values:
      layout: default
  - scope:
      path: ''
      type: 'partner_success_stories'
    values:
      layout: default
  - scope:
      path: ''
      type: 'partner_api'
    values:
      layout: default
