# Settings
title: Zapier Platform UI Documentation
description: "Zapier Platform UI"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
baseurl: ""

plugins:
- jekyll-redirect-from
- jekyll-sitemap

# Sass Settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: docs

collections:
  quickstart:
    output: true
    permalink: /:collection/:name
  docs:
    output: true
    permalink: /:collection/:name
  news:
    output: true
    permalink: /:collection/:name
  cli_tutorials:
    output: true
    permalink: /:collection/:name
  legacy:
    output: true
    permalink: /:collection/:name


defaults:
  - scope:
      path: ""
      type: "quickstart"
    values:
      layout: default
  - scope:
      path: ""
      type: "docs"
    values:
      layout: default      
  - scope:
      path: ""
      type: "news"
    values:
      layout: default  
  - scope:
      path: ""
      type: "cli_tutorials"
    values:
      layout: default
  - scope:
      path: ""
      type: "legacy"
    values:
      layout: default
